const test = require('node:test');
const assert = require('node:assert/strict');
const { once } = require('node:events');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const http = require('node:http');
const { Server } = require('socket.io');
const { io: connect } = require('socket.io-client');
const registerQuestions = require('../questions');

test('live questions synchronize, enforce speaker access, and survive restarts', async t => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'qna-test-'));
  const dataFile = path.join(directory, 'questions.json');
  let io;
  const clients = [];
  const start = async () => {
    const server = http.createServer();
    io = new Server(server);
    registerQuestions(io, dataFile);
    server.listen(0, '127.0.0.1');
    await once(server, 'listening');
    return `http://127.0.0.1:${server.address().port}`;
  };
  const client = async url => {
    const socket = connect(url, { transports: ['websocket'], reconnection: false });
    clients.push(socket);
    await once(socket, 'connect');
    return socket;
  };
  const emit = (socket, event, data) => new Promise((resolve, reject) => {
    socket.timeout(2000).emit(event, data, (error, result) => error ? reject(error) : resolve(result));
  });
  t.after(async () => {
    clients.forEach(socket => socket.disconnect());
    await new Promise(resolve => io.close(resolve));
    fs.rmSync(directory, { recursive: true, force: true });
  });
  const url = await start();
  const speaker = await client(url);
  const guest = await client(url);
  const display = await client(url);
  const other = await client(url);
  assert.equal((await emit(speaker, 'qna-create', { title: 123 })).success, false);
  const board = await emit(speaker, 'qna-create', { title: 'Conference Q&A' });
  assert.equal(board.success, true);
  const { code, hostToken } = board;
  const joined = await emit(guest, 'qna-join', { code: code.toLowerCase() });
  assert.equal(joined.isHost, false);
  assert.equal('hostToken' in joined, false);
  assert.equal('hostHash' in joined, false);
  await emit(display, 'qna-join', { code });
  const isolated = await emit(other, 'qna-create', { title: 'Other room' });
  let unrelatedUpdates = 0;
  other.on('qna-update', () => unrelatedUpdates++);
  const speakerUpdate = once(speaker, 'qna-update');
  const displayUpdate = once(display, 'qna-update');
  const payload = { code, text: 'How does this work?', requestId: 'question-1' };
  assert.equal((await emit(guest, 'qna-submit', payload)).success, true);
  assert.equal((await speakerUpdate)[0].questions[0].text, payload.text);
  assert.equal((await displayUpdate)[0].questions[0].name, 'Anonymous');
  assert.equal(unrelatedUpdates, 0);
  assert.equal((await emit(guest, 'qna-submit', payload)).success, true);
  assert.equal((await emit(guest, 'qna-join', { code })).questions.length, 1);
  assert.equal((await emit(guest, 'qna-submit', { ...payload, text: 'x'.repeat(501), requestId: 'invalid' })).success, false);
  assert.equal((await emit(guest, 'qna-submit', { ...payload, requestId: 'too-fast' })).success, false);
  assert.equal((await emit(guest, 'qna-delete', { code, questionId: 'question-1' })).success, false);
  assert.equal((await emit(guest, 'qna-delete', { code, hostToken: 'fake', questionId: 'question-1' })).success, false);
  assert.equal((await emit(guest, 'qna-submit', { ...payload, code: isolated.code })).success, false);
  guest.disconnect(); speaker.disconnect();
  assert.equal((await emit(display, 'qna-join', { code })).questions.length, 1);
  clients.forEach(socket => socket.disconnect());
  await new Promise(resolve => io.close(resolve));
  const restartedUrl = await start();
  const recoveredSpeaker = await client(restartedUrl);
  const recoveredDisplay = await client(restartedUrl);
  const recovered = await emit(recoveredSpeaker, 'qna-join', { code, hostToken });
  assert.equal(recovered.isHost, true);
  assert.equal(recovered.questions.length, 1);
  await emit(recoveredDisplay, 'qna-join', { code });
  const deletion = once(recoveredDisplay, 'qna-update');
  assert.equal((await emit(recoveredSpeaker, 'qna-delete', { code, hostToken, questionId: 'question-1' })).success, true);
  assert.deepEqual((await deletion)[0].questions, []);
  assert.deepEqual(JSON.parse(fs.readFileSync(dataFile, 'utf8')).find(b => b.code === code).questions, []);
});
